services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    # override the start command:
    command: sh -c "npm install && npm run dev"
    environment:
      - VITE_APP_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - backend/.env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/go_modules
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=supersecret
      - DB_NAME=soundsphere

      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD= # leave blank if no password
      - REDIS_DB=0
    depends_on:
      - database
      - redis
    networks:
      - app-network

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: postgres # Ensure this matches the user you're trying to use
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: soundsphere # The default database that will be created
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  frontend_node_modules:
  redis_data:

networks:
  app-network:
    driver: bridge
