version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VUE_APP_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/go_modules
    environment:
      - DB_HOST=database
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
