<template>
  <main>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
    <h1>Example</h1>
  </main>
</template>

<script setup lang="ts"></script>
