<template>
  <main>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
    <h1>Beishpiel</h1>
  </main>
</template>

<script setup lang="ts"></script>
